version: '3.7'

services:
  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - app_net
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - app_net

networks:
  app_net:
    external: true
    name: app_net
