"""empty message

Revision ID: d3363067e530
Revises: 
Create Date: 2022-11-19 08:50:19.486562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3363067e530'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_passports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passport_id', sa.String(), nullable=False),
    sa.Column('vin_id', sa.String(), nullable=False),
    sa.Column('auto_model', sa.String(), nullable=False),
    sa.Column('body_color', sa.String(), nullable=False),
    sa.Column('engine_type', sa.String(), nullable=False),
    sa.Column('validated', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('second_name', sa.String(length=50), nullable=False),
    sa.Column('third_name', sa.String(length=50), nullable=False),
    sa.Column('esia_id', sa.String(), nullable=True),
    sa.Column('auto_passport_ids', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('auto_passports')
    # ### end Alembic commands ###
